---
- name: test ansible things
  hosts: 127.0.0.1
  become: true
  tasks:
    - name: print working directory
      command: pwd
    - name: copy file from ? to ?
      copy: src=/home/phillip/Desktop/pom.xml dest=/home/phillip/Downlods/
      register: result_copy
    - debug: msg=result_copy
