---
# tasks file for start_liberty_server

#check server status

- name: check server status
  command: "sh {{ server_directory }}bin/serverStatus.sh {{ server_name }} -user {{ server_user }} -password {{ server_user_password }}"
  register: server_status

- debug: var=server_status

- name: start server {{ server_name }}
  command: "sh {{ server_directory }}bin/startServer.sh {{ server_name }} -user {{ server_user }} -password {{ server_user_password }}"
  when: ("is not running" in server_status.stdout) or ("cannot be reached" in server_status.stdout)
  register: start_server_result

- debug: var=start_server_result
